name: build-push-docker-hub

on:
  workflow_dispatch:
    # Pseudo inputs
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

  push:
    branches: coronahit
    paths:
      - 'Dockerfile'
      - '!README.md'
      - '!app/data/*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_KEY }}
      - 
        name: Github checkout
        uses: actions/checkout@v2
        with:
          ref: coronahit
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          push: true
          context: .
          tags: quadram/artic-coronahit:latest
          cache-from: type=registry,ref=quadram/artic-coronahit:latest
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}